# Generated by Django 3.2.25 on 2024-06-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['updatedAt']},
        ),
    ]
